Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptDir "..")
$autoMemoryDir = Join-Path $repoRoot ".github/auto-memory"
$configPath = Join-Path $autoMemoryDir "config.json"
$dirtyPath = Join-Path $autoMemoryDir "dirty-files"

if (-not (Test-Path $autoMemoryDir)) {
    New-Item -ItemType Directory -Path $autoMemoryDir -Force | Out-Null
}

if (-not (Test-Path $configPath)) {
    '{"triggerMode":"default"}' | Out-File -FilePath $configPath -Encoding utf8
}

$triggerMode = "default"
try {
    $config = Get-Content -Path $configPath -Raw | ConvertFrom-Json
    if ($null -ne $config.triggerMode -and $config.triggerMode -ne "") {
        $triggerMode = [string]$config.triggerMode
    }
} catch {
    $triggerMode = "default"
}

$dirtyAbsolute = New-Object System.Collections.Generic.List[string]
$rawStatus = git -C $repoRoot status --porcelain

foreach ($line in $rawStatus) {
    if ([string]::IsNullOrWhiteSpace($line)) {
        continue
    }

    # porcelain format: XY<space>path or XY<space>old -> new
    $entry = $line.Substring(3).Trim()
    if ($entry -like "* -> *") {
        $entry = $entry.Split(" -> ")[-1].Trim()
    }

    if ($entry.StartsWith('"') -and $entry.EndsWith('"')) {
        $entry = $entry.Trim('"')
    }

    $fullPath = Join-Path $repoRoot $entry

    if (Test-Path $fullPath) {
        $item = Get-Item -Path $fullPath
        if ($item.PSIsContainer) {
            $files = Get-ChildItem -Path $fullPath -File -Recurse
            foreach ($file in $files) {
                $dirtyAbsolute.Add($file.FullName)
            }
        } else {
            $dirtyAbsolute.Add($item.FullName)
        }
    } else {
        # Keep unresolved path as absolute candidate for deleted files
        $dirtyAbsolute.Add((Join-Path $repoRoot $entry))
    }
}

$normalized = @(
    $dirtyAbsolute |
        Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
        ForEach-Object { $_.Trim() } |
        Select-Object -Unique
)

$outputLines = @(
    "# Dirty Files",
    "",
    "Generated by scripts/auto-memory-sync.ps1",
    ""
) + $normalized

$outputLines | Out-File -FilePath $dirtyPath -Encoding utf8

Write-Host "auto-memory: triggerMode=$triggerMode" -ForegroundColor Cyan
Write-Host "auto-memory: dirty files synced to $dirtyPath" -ForegroundColor Green
Write-Host ("auto-memory: tracked entries = {0}" -f ($normalized.Count)) -ForegroundColor Green
