#!/usr/bin/env python3
"""Cross-platform auto-memory sync for dirty files snapshot."""

from __future__ import annotations

import json
import platform
import subprocess
import sys
from pathlib import Path


DEFAULT_CONFIG = {"triggerMode": "default"}


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def ensure_auto_memory_paths(root: Path) -> tuple[Path, Path]:
    auto_memory_dir = root / ".github" / "auto-memory"
    config_path = auto_memory_dir / "config.json"
    dirty_path = auto_memory_dir / "dirty-files"

    auto_memory_dir.mkdir(parents=True, exist_ok=True)
    if not config_path.exists():
        config_path.write_text(json.dumps(DEFAULT_CONFIG), encoding="utf-8")

    return config_path, dirty_path


def read_trigger_mode(config_path: Path) -> str:
    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
        trigger_mode = str(config.get("triggerMode", "")).strip()
        return trigger_mode or "default"
    except Exception:
        return "default"


def get_git_status_lines(root: Path) -> list[str]:
    cmd = ["git", "-C", str(root), "status", "--porcelain"]
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        err = result.stderr.strip() or "unknown error"
        print(
            f"auto-memory: warning: git status failed ({result.returncode}): {err}",
            file=sys.stderr,
        )
        return []
    return result.stdout.splitlines()


def normalize_status_entry(line: str) -> str | None:
    if len(line) < 4:
        return None

    entry = line[3:].strip()
    if not entry:
        return None

    if " -> " in entry:
        entry = entry.split(" -> ", 1)[1].strip()

    if entry.startswith('"') and entry.endswith('"'):
        entry = entry[1:-1]

    return entry


def expand_entry_to_files(root: Path, entry: str) -> list[str]:
    candidate = (root / entry).resolve()

    if candidate.exists():
        if candidate.is_dir():
            return [str(path.resolve()) for path in candidate.rglob("*") if path.is_file()]
        return [str(candidate)]

    # Keep unresolved absolute path for deleted files.
    return [str(candidate)]


def collect_dirty_files(root: Path) -> list[str]:
    absolute_paths: set[str] = set()

    for line in get_git_status_lines(root):
        entry = normalize_status_entry(line)
        if not entry:
            continue

        for path in expand_entry_to_files(root, entry):
            if path.strip():
                absolute_paths.add(path.strip())

    return sorted(absolute_paths, key=str.casefold)


def write_dirty_snapshot(dirty_path: Path, dirty_files: list[str]) -> None:
    lines = [
        "# Dirty Files",
        "",
        "Generated by scripts/auto_memory_sync.py",
        "",
        *dirty_files,
    ]
    dirty_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    root = repo_root()
    config_path, dirty_path = ensure_auto_memory_paths(root)
    trigger_mode = read_trigger_mode(config_path)

    dirty_files = collect_dirty_files(root)
    write_dirty_snapshot(dirty_path, dirty_files)

    os_name = platform.system() or "unknown"
    print(f"auto-memory: os={os_name} triggerMode={trigger_mode}")
    print(f"auto-memory: dirty files synced to {dirty_path}")
    print(f"auto-memory: tracked entries = {len(dirty_files)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
