"""Pydantic v2 request/response schemas for the POST /api/v1/analyze endpoint."""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field, field_validator


class AnalyzeRequest(BaseModel):
    url: str = Field(..., min_length=1, max_length=2048)
    email_hash: str | None = None  # SHA-256 hash of the email (privacy)
    email_body_snippet: str | None = Field(None, max_length=5000)

    @field_validator("url")
    @classmethod
    def validate_url(cls, v: str) -> str:
        v = v.strip()
        if not (v.startswith("http://") or v.startswith("https://")):
            raise ValueError("URL must start with http:// or https://")
        return v


class IDNResult(BaseModel):
    domain_unicode: str
    confusable_chars: list[str]
    homograph_ratio: float
    visual_similarity: float
    s_idn_local: float
    is_mixed_script: bool
    is_suspicious: bool


class TIResult(BaseModel):
    s_vt: float
    s_urlscan: float
    s_gsb: float
    s_ti: float
    # WhoisXML domain age fields
    domain_age_days: int | None = None    # None si no disponible
    is_newly_registered: bool = False      # True si < DOMAIN_AGE_SUSPICIOUS_DAYS
    whois_registrar: str | None = None


class AgentScores(BaseModel):
    s_idn_local: float
    s_ti: float
    s_idn: float
    s_llm: float
    s_hf: float = 0.5   # HuggingFace classifier score; 0.5 (neutral) when key absent
    s_risk: float


class ShapExplanation(BaseModel):
    feature_contributions: dict[str, float]


class EmailSignals(BaseModel):
    """Señales extraídas del contexto del email completo (cabeceras + cuerpo)."""

    subject: str = ""
    sender: str = ""
    sender_domain: str = ""
    return_path_domain: str = ""
    sender_domain_mismatch: bool = False
    has_suspicious_attachments: bool = False
    is_urgent: bool = False
    urgency_score: float = Field(default=0.0, ge=0.0, le=1.0)
    spf_pass: bool = False
    dkim_pass: bool = False
    extracted_urls: list[str] = Field(default_factory=list)
    attachment_names: list[str] = Field(default_factory=list)


class AnalyzeResponse(BaseModel):
    request_id: str
    url: str
    domain: str
    verdict: Literal["PHISHING", "LEGITIMATE", "SUSPICIOUS"]
    s_risk: float = Field(ge=0.0, le=1.0)
    agent_scores: AgentScores
    idn_result: IDNResult
    ti_result: TIResult
    llm_reason: str
    shap_explanation: ShapExplanation
    # Reasons generated by FusionAgent from same thresholds as verdict (not derived in frontend)
    reasons: list[str] = Field(default_factory=list)
    processing_ms: float
    timestamp: datetime


class EmailAnalysisResponse(BaseModel):
    """Respuesta del pipeline de análisis de email completo (.eml/.msg)."""

    email_hash: str
    email_signals: EmailSignals
    url_analyses: list[AnalyzeResponse]
    email_verdict: Literal["PHISHING", "LEGITIMATE", "SUSPICIOUS"]
    email_s_risk: float = Field(ge=0.0, le=1.0)
    reasons: list[str] = Field(default_factory=list)
    processing_ms: float
    timestamp: datetime
