"""Pydantic v2 request/response schemas for the POST /api/v1/analyze endpoint."""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field, field_validator


class AnalyzeRequest(BaseModel):
    url: str = Field(..., min_length=1, max_length=2048)
    email_hash: str | None = None
    email_body_snippet: str | None = Field(None, max_length=5000)
    # Email context forwarded by the extension (for display in the admin dashboard)
    email_subject: str | None = None
    email_from: str | None = None
    email_to: str | None = None
    all_urls: list[str] = Field(default_factory=list, max_length=50)

    @field_validator("url")
    @classmethod
    def validate_url(cls, v: str) -> str:
        v = v.strip()
        if not (v.startswith("http://") or v.startswith("https://")):
            raise ValueError("URL must start with http:// or https://")
        return v


class IDNResult(BaseModel):
    domain_unicode: str
    confusable_chars: list[str]
    homograph_ratio: float
    visual_similarity: float
    s_idn_local: float
    is_mixed_script: bool
    is_suspicious: bool


class TIResult(BaseModel):
    s_vt: float
    s_urlscan: float
    s_gsb: float
    s_ti: float
    # WhoisXML domain age fields
    domain_age_days: int | None = None    # None si no disponible
    is_newly_registered: bool = False      # True si < DOMAIN_AGE_SUSPICIOUS_DAYS
    whois_registrar: str | None = None


class WebProbeResult(BaseModel):
    """Signals extracted by active URL probing (WebProbeAgent)."""

    final_url: str = ""
    final_domain: str = ""
    status_code: int = 0
    redirect_count: int = 0
    has_password_field: bool = False
    has_login_form: bool = False
    domain_changed_on_redirect: bool = False
    brand_impersonation: str | None = None
    external_form_action: bool = False
    s_probe: float = Field(default=0.0, ge=0.0, le=1.0)
    probe_signals: list[str] = Field(default_factory=list)
    error: str | None = None   # set when probe could not complete


class AgentScores(BaseModel):
    s_idn_local: float
    s_ti: float
    s_idn: float
    s_llm: float
    s_hf: float = 0.5   # HuggingFace classifier score; 0.5 (neutral) when key absent
    s_probe: float = 0.0  # WebProbeAgent active-probe score; 0.0 when probe fails
    s_risk: float


class ShapExplanation(BaseModel):
    feature_contributions: dict[str, float]


class EmailSignals(BaseModel):
    """Señales extraídas del contexto del email completo (cabeceras + cuerpo)."""

    subject: str = ""
    sender: str = ""
    sender_domain: str = ""
    return_path_domain: str = ""
    sender_domain_mismatch: bool = False
    has_suspicious_attachments: bool = False
    is_urgent: bool = False
    urgency_score: float = Field(default=0.0, ge=0.0, le=1.0)
    spf_pass: bool = False
    dkim_pass: bool = False
    extracted_urls: list[str] = Field(default_factory=list)
    attachment_names: list[str] = Field(default_factory=list)


class AnalyzeResponse(BaseModel):
    request_id: str
    url: str
    domain: str
    verdict: Literal["PHISHING", "LEGITIMATE", "SUSPICIOUS"]
    s_risk: float = Field(ge=0.0, le=1.0)
    agent_scores: AgentScores
    idn_result: IDNResult
    ti_result: TIResult
    probe_result: WebProbeResult | None = None
    llm_reason: str
    shap_explanation: ShapExplanation
    # Reasons generated by FusionAgent from same thresholds as verdict (not derived in frontend)
    reasons: list[str] = Field(default_factory=list)
    processing_ms: float
    timestamp: datetime


class EmailAnalysisResponse(BaseModel):
    """Respuesta del pipeline de análisis de email completo (.eml/.msg)."""

    email_hash: str
    email_signals: EmailSignals
    url_analyses: list[AnalyzeResponse]
    email_verdict: Literal["PHISHING", "LEGITIMATE", "SUSPICIOUS"]
    email_s_risk: float = Field(ge=0.0, le=1.0)
    reasons: list[str] = Field(default_factory=list)
    processing_ms: float
    timestamp: datetime


class BatchAnalyzeRequest(BaseModel):
    """Analiza múltiples URLs de un correo en una sola llamada."""

    urls: list[str] = Field(..., min_length=1, max_length=10)
    email_hash: str | None = None
    email_body_snippet: str | None = Field(None, max_length=5000)
    email_subject: str | None = None
    email_from: str | None = None
    email_to: str | None = None

    @field_validator("urls")
    @classmethod
    def validate_urls(cls, v: list[str]) -> list[str]:
        for url in v:
            url = url.strip()
            if not (url.startswith("http://") or url.startswith("https://")):
                raise ValueError(f"URL must start with http:// or https://: {url}")
        return v


class BatchAnalyzeResponse(BaseModel):
    """Resultado de analizar múltiples URLs en paralelo."""

    url_analyses: list[AnalyzeResponse]
    worst: AnalyzeResponse  # URL con el s_risk más alto
    processing_ms: float
    timestamp: datetime


class AnalyzeEmailRequest(BaseModel):
    """Request from the browser extension — full email content for batch URL analysis."""

    email_subject: str = Field(..., max_length=500)
    email_from: str = Field(..., max_length=300)
    email_to: str = Field(..., max_length=300)
    email_body_html: str = Field(..., max_length=200_000)
    email_text_snippet: str = Field(..., max_length=5000)
    email_hash: str | None = None
    all_urls: list[str] = Field(default_factory=list, max_length=35)
    images: list[str] = Field(default_factory=list, max_length=50)
    attachments: list[str] = Field(default_factory=list, max_length=20)
    header_date: str | None = None

    @field_validator("all_urls")
    @classmethod
    def validate_all_urls(cls, v: list[str]) -> list[str]:
        if len(v) > 35:
            raise ValueError("Maximum 35 URLs per email")
        for url in v:
            if not url.startswith(("http://", "https://")):
                raise ValueError(f"Invalid URL: {url}")
        return v


class AnalyzeEmailResponse(BaseModel):
    """Response from /analyze_email — all URL verdicts + aggregated email verdict."""

    url_analyses: list[AnalyzeResponse]
    worst: AnalyzeResponse
    email_verdict: Literal["PHISHING", "LEGITIMATE", "SUSPICIOUS"]
    reasons: list[str] = Field(default_factory=list)
    processing_ms: float
    timestamp: datetime


class ReportRequest(BaseModel):
    url: str = Field(..., min_length=1, max_length=2048)
    reporter_note: str = Field(default="", max_length=500)
    reported_verdict: Literal["PHISHING", "SUSPICIOUS"] = "PHISHING"


class ReportResponse(BaseModel):
    report_id: str
    url: str
    reported_verdict: str
    message: str
    timestamp: datetime
